/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uptc.proveedores.vista;

import co.edu.uptc.proveedores.controlador.ControladorPrincipal;
import co.edu.uptc.proveedores.modelo.Canal;
import co.edu.uptc.proveedores.modelo.Plan;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fredy
 */
public class CanalVistaPanel extends javax.swing.JPanel {

    private DefaultTableModel defaultTableModel;
    private DefaultListModel<String> defaultListModel;
    private Set<Plan> planes;

    /**
     * Creates new form CanalVistaPanel
     */
    public CanalVistaPanel(ControladorPrincipal controladorPrincipal) {
        initComponents();
        initActions(controladorPrincipal);
        initTabla();
        this.planes = new HashSet<>();
        this.defaultListModel = new DefaultListModel<>();
        this.listPlanes.setModel(defaultListModel);
    }

    private void initActions(ControladorPrincipal controladorPrincipal) {
        this.btnActualizar.setActionCommand(ControladorPrincipal.ACCION_ACTUALIZAR_CANAL);
        this.btnAgregar.setActionCommand(ControladorPrincipal.ACCION_AGREGAR_CANAL);
        this.btnAgregarPlan.setActionCommand(ControladorPrincipal.ACCION_AGREGAR_CANAL_PLAN);
        this.btnConsultar.setActionCommand(ControladorPrincipal.ACCION_CONSULTAR_CANAL);
        this.btnEliminar.setActionCommand(ControladorPrincipal.ACCION_ELIMINAR_CANAL);
        this.btnActualizar.addActionListener(controladorPrincipal);
        this.btnAgregar.addActionListener(controladorPrincipal);
        this.btnAgregarPlan.addActionListener(controladorPrincipal);
        this.btnConsultar.addActionListener(controladorPrincipal);
        this.btnEliminar.addActionListener(controladorPrincipal);
    }

    private void initTabla() {
        this.defaultTableModel = new DefaultTableModel();
        this.defaultTableModel.addColumn("Código");
        this.defaultTableModel.addColumn("Nombre");
        this.defaultTableModel.addColumn("Tipo");
        this.defaultTableModel.addColumn("Planes");
        this.defaultTableModel.addColumn("Logo");
        this.tablaCanales.setModel(defaultTableModel);
    }

    public void limpiarFormulario() {
        this.inputCodigo.setValue(0);
        this.inputLogo.setText("");
        this.inputNombre.setText("");
        this.inputTipo.setText("");
        this.defaultListModel.removeAllElements();
        this.planes = new HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JSpinner();
        lblNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        inputLogo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlanes = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCanales = new javax.swing.JTable();
        btnEliminarPlan = new javax.swing.JButton();
        btnAgregarPlan = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        inputTipo = new javax.swing.JTextField();

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CANALES");

        lblCodigo.setText("Código:");

        lblNombre.setText("Nombre:");

        lblLogo.setText("Logo:");

        jLabel4.setText("Planes:");

        jScrollPane1.setViewportView(listPlanes);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar);

        btnConsultar.setText("Consultar");
        jPanel1.add(btnConsultar);

        btnActualizar.setText("Actualizar");
        jPanel1.add(btnActualizar);

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);

        tablaCanales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCanales);

        btnEliminarPlan.setText("-");
        btnEliminarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlanActionPerformed(evt);
            }
        });

        btnAgregarPlan.setText("+");

        lblTipo.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPlan))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCodigo)
                            .addComponent(inputNombre)
                            .addComponent(inputLogo)
                            .addComponent(inputTipo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputCodigo)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputNombre)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputLogo)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(inputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarPlan)
                        .addComponent(btnAgregarPlan))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlanActionPerformed
        // TODO add your handling code here:
        this.eliminarPlanSeleccionado();
    }//GEN-LAST:event_btnEliminarPlanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarPlan;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPlan;
    private javax.swing.JSpinner inputCodigo;
    private javax.swing.JTextField inputLogo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listPlanes;
    private javax.swing.JTable tablaCanales;
    // End of variables declaration//GEN-END:variables

    public void agregarPlan(Plan plan) {
        this.planes.add(plan);
        this.defaultListModel.add(0, plan.getNombre());
    }

    public Canal getCanal() {
        Canal canal = new Canal();
        canal.setCodigo((Integer) inputCodigo.getValue());
        canal.setNombre(inputNombre.getText());
        canal.setLogo(inputLogo.getText());
        canal.setTipo(inputTipo.getText());
        canal.setPlanes(this.planes);
        return canal;
    }

    public void eliminarPlanSeleccionado() {
        int index = this.listPlanes.getSelectedIndex();
        if (index >= 0) {
            Plan plan = (Plan) this.planes.toArray()[index];
            this.planes.remove(plan);
            this.defaultListModel.removeElement(plan.getNombre());
        }
    }

    public void setCanales(List<Canal> canales) {
        this.defaultTableModel.setRowCount(0);
        for (Canal canal : canales) {
            this.defaultTableModel.addRow(new Object[]{canal.getCodigo(),
                canal.getNombre(), canal.getTipo(), canal.getPlanes().size(),
                canal.getLogo()});
        }
    }

    public void setCanal(Canal canal) {
        this.inputCodigo.setValue(canal.getCodigo());
        this.inputLogo.setText(canal.getLogo());
        this.inputNombre.setText(canal.getNombre());
        this.inputTipo.setText(canal.getTipo());
        this.planes = canal.getPlanes();
        this.defaultListModel.removeAllElements();
        for (Plan plan : canal.getPlanes()) {
            this.defaultListModel.addElement(plan.getNombre());
        }
    }

}
