/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uptc.proveedores.vista;

import co.edu.uptc.proveedores.controlador.ControladorPrincipal;
import co.edu.uptc.proveedores.modelo.Origen;
import co.edu.uptc.proveedores.modelo.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fredy
 */
public class ProductoVistaPanel extends javax.swing.JPanel {

    private DefaultTableModel modelProductos;

    /**
     * Creates new form ProductoVistaPanel
     */
    public ProductoVistaPanel(ControladorPrincipal controladorPrincipal) {
        initComponents();
        this.initActions(controladorPrincipal);
        this.modelProductos = new DefaultTableModel();
        this.tableProductos.setModel(modelProductos);
        this.modelProductos.setColumnIdentifiers(new String[]{"Código",
            "Descripción", "Tipo producto", "Cargo"});
    }

    private void initActions(ControladorPrincipal controladorPrincipal) {
        this.btnAgregar.setActionCommand(ControladorPrincipal.ACCION_AGREGAR_PRODUCTO);
        this.btnAgregar.addActionListener(controladorPrincipal);
        this.btnConsultar.setActionCommand(ControladorPrincipal.ACCION_CONSULTAR_PRODUCTO);
        this.btnConsultar.addActionListener(controladorPrincipal);
        this.btnActualizar.addActionListener(controladorPrincipal);
        this.btnActualizar.setActionCommand(ControladorPrincipal.ACCION_ACTUALIZAR_PRODUCTO);
        this.btnEliminar.addActionListener(controladorPrincipal);
        this.btnEliminar.setActionCommand(ControladorPrincipal.ACCION_ELIMINAR_PRODUCTO);
    }

    public void limpiarFormulario() {
        this.inputCodigo.setValue(0);
        this.inputCargo.setValue(0);
        this.inputDescripcion.setText("");
        this.inputOrigen.setSelectedItem(null);
        this.inputTipoProducto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        inputDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputCargo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        inputOrigen = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputTipoProducto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS");

        jLabel2.setText("Código:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Cargo:");

        jLabel5.setText("Origen:");

        jLabel6.setText("Tipo producto:");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar);

        btnConsultar.setText("Consultar");
        jPanel1.add(btnConsultar);

        btnActualizar.setText("Actualizar");
        jPanel1.add(btnActualizar);

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCodigo)
                            .addComponent(inputDescripcion)
                            .addComponent(inputCargo)
                            .addComponent(inputOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTipoProducto)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inputCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(inputOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(inputTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JSpinner inputCargo;
    private javax.swing.JSpinner inputCodigo;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JComboBox<Origen> inputOrigen;
    private javax.swing.JTextField inputTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProductos;
    // End of variables declaration//GEN-END:variables

    public Producto getProducto() {
        Producto producto = new Producto();
        producto.setCargo((Integer) this.inputCargo.getValue());
        producto.setCodigo((Integer) this.inputCodigo.getValue());
        producto.setDescripcion(this.inputDescripcion.getText());
        producto.setTipoProducto(this.inputTipoProducto.getText());
        Object origen = this.inputOrigen.getSelectedItem();
        if (origen != null) {
            producto.setOrigen((Origen) origen);
        }
        return producto;
    }

    public void setOrigenes(List<Origen> origenes) {
        this.inputOrigen.removeAllItems();
        this.inputOrigen.addItem(null);
        for (Origen origen : origenes) {
            this.inputOrigen.addItem(origen);
        }
    }

    public void setProductos(List<Producto> productos) {
        this.modelProductos.setRowCount(0);
        for (Producto producto : productos) {
            this.modelProductos.addRow(new Object[]{producto.getCodigo(),
                producto.getDescripcion(), producto.getTipoProducto(),
                producto.getCargo()});
        }
    }

    public void setProducto(Producto producto) {
        this.inputCodigo.setValue(producto.getCodigo());
        this.inputCargo.setValue(producto.getCargo());
        this.inputDescripcion.setText(producto.getDescripcion());
        this.inputOrigen.setSelectedItem(producto.getOrigen());
        this.inputTipoProducto.setText(producto.getTipoProducto());
        Origen origenProducto = producto.getOrigen();
        if (origenProducto != null) {
            Origen origen;
            for (int i = 0; i < this.inputOrigen.getItemCount(); i++) {
                origen = this.inputOrigen.getItemAt(i);
                if (origen != null && this.inputOrigen.getItemAt(i).toString()
                        .equals(origenProducto.toString())) {
                    this.inputOrigen.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

}
