/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uptc.proveedores.vista;

import co.edu.uptc.proveedores.controlador.ControladorPrincipal;

/**
 *
 * @author fredy
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private ControladorPrincipal controladorPrincipal = new ControladorPrincipal();
    
    /**
     * Creates new form VistaPrinicipal
     */
    public VistaPrincipal() {
        initComponents();
        menuProveedor.addActionListener(controladorPrincipal);
        menuMarca.addActionListener(controladorPrincipal);
        menuProveedorMarca.addActionListener(controladorPrincipal);
        menuCanal.addActionListener(controladorPrincipal);
        menuPlan.addActionListener(controladorPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProveedor = new javax.swing.JMenuItem();
        menuMarca = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuProveedorMarca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPlan = new javax.swing.JMenuItem();
        menuCanal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO DE PROVEEDORES");

        jMenu1.setText("Datos básicos");

        menuProveedor.setText("Proveedor");
        menuProveedor.setActionCommand(ControladorPrincipal.ACTION_PROVEEDOR);
        jMenu1.add(menuProveedor);

        menuMarca.setText("Marca");
        jMenu1.add(menuMarca);
        jMenu1.add(jSeparator2);

        menuProveedorMarca.setText("Proveedor marca");
        menuProveedorMarca.setActionCommand(ControladorPrincipal.ACTION_PROVEEDOR_MARCA);
        jMenu1.add(menuProveedorMarca);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Planes");

        menuPlan.setText("Plan");
        jMenu2.add(menuPlan);

        menuCanal.setText("Canal");
        menuCanal.setActionCommand(ControladorPrincipal.ACTION_PLAN_CANAL);
        jMenu2.add(menuCanal);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Productos");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuCanal;
    private javax.swing.JMenuItem menuMarca;
    private javax.swing.JMenuItem menuPlan;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuProveedorMarca;
    // End of variables declaration//GEN-END:variables
}
